"""full_model_redesign_v2

Revision ID: 12c9a81160b7
Revises: a5d7f59e21c1
Create Date: 2026-04-05 08:00:41.690151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12c9a81160b7'
down_revision: Union[str, Sequence[str], None] = 'a5d7f59e21c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('context_id', sa.String(), nullable=True),
    sa.Column('is_temporary', sa.Boolean(), nullable=True),
    sa.Column('delete_after', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_url')
    )
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True, comment='ผู้ทำ action — NULL = system/automated'),
    sa.Column('event', sa.String(length=60), nullable=False, comment='ActivityEvent enum value'),
    sa.Column('subject_type', sa.String(length=40), nullable=True, comment='entity ที่เกิด event: job | proposal | project | milestone | dispute'),
    sa.Column('subject_id', sa.UUID(), nullable=True, comment='id ของ entity นั้น'),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='ข้อมูล denormalized สำหรับแสดงผล feed โดยไม่ต้อง JOIN เช่น {title, amount, username}'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_actor', 'activity_logs', ['actor_id'], unique=False)
    op.create_index('ix_activity_created', 'activity_logs', ['created_at'], unique=False)
    op.create_index('ix_activity_event', 'activity_logs', ['event'], unique=False)
    op.create_index('ix_activity_subject', 'activity_logs', ['subject_type', 'subject_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='ผู้ทำ action — NULL = system/automated'),
    sa.Column('action', sa.String(length=60), nullable=False, comment='AuditAction enum value'),
    sa.Column('resource_type', sa.String(length=40), nullable=True, comment='user | kyc | payment | dispute ฯลฯ'),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='ค่าเดิมก่อน action — สำหรับ change tracking'),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='ค่าใหม่หลัง action'),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='IP ของ request'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Browser/client ที่ใช้'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='context เพิ่มเติม สำหรับ debug'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False, comment='ผู้เขียนโพสต์'),
    sa.Column('category', sa.String(), nullable=True, comment='ประเภทโพสต์ เช่น general | artwork | coding | design | writing'),
    sa.Column('content', sa.Text(), nullable=True, comment='เนื้อหาโพสต์ (text)'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='true = แสดงสาธารณะ, false = เฉพาะตัวเอง'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='จำนวน view แบบ denormalized — increment ที่ service layer ด้วย UPDATE ... SET view_count = view_count + 1'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='วันที่สร้างโพสต์'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='วันที่ DB row ถูก touch ล่าสุด (รวมถึงการ increment view_count)'),
    sa.Column('edited_at', sa.DateTime(), nullable=True, comment="วันที่ user แก้ไข content จริงๆ — set manual ที่ service layer เท่านั้น แสดงบน UI ว่า 'แก้ไขแล้ว'"),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='soft delete — ถ้ามีค่าหมายถึงถูกลบแล้ว'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_community_posts_author_id', 'community_posts', ['author_id'], unique=False)
    op.create_index('ix_community_posts_category', 'community_posts', ['category'], unique=False)
    op.create_index('ix_community_posts_created_at', 'community_posts', ['created_at'], unique=False)
    op.create_table('file_access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('citizen_id', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False, comment='pending | verified | rejected'),
    sa.Column('reviewed_by', sa.UUID(), nullable=True, comment='Admin user ที่ตรวจสอบ'),
    sa.Column('review_note', sa.Text(), nullable=True, comment='เหตุผลที่ reject หรือ note จาก admin'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_kyc_profiles_status', 'kyc_profiles', ['status'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False, comment='NotificationType enum value'),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notification_type', name='uq_notification_setting')
    )
    op.create_index('ix_notification_settings_user', 'notification_settings', ['user_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gateway_provider', sa.String(length=20), nullable=False, comment='omise | stripe | promptpay | manual'),
    sa.Column('gateway_tx_id', sa.String(length=255), nullable=True, comment='Transaction ID จาก provider เช่น chrg_xxx (Omise) / pi_xxx (Stripe). NULL = manual'),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full webhook body จาก gateway — เก็บไว้สำหรับ debug / reconcile'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='charge | transfer | refund | reversal'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False, comment='platform fee หรือ gateway fee ที่หักออก'),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='amount - fee = ยอดสุทธิที่ผู้รับได้จริง'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='เจ้าของรายการ — client (charge/refund) หรือ freelancer (transfer)'),
    sa.Column('reference_type', sa.String(length=30), nullable=True, comment='milestone | project | dispute'),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('gateway_created_at', sa.DateTime(), nullable=True, comment='เวลาที่ gateway สร้าง transaction (จาก webhook payload)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_provider', 'gateway_tx_id', name='uq_gateway_tx')
    )
    op.create_index('ix_payment_tx_reference', 'payment_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_payment_tx_status', 'payment_transactions', ['status'], unique=False)
    op.create_index('ix_payment_tx_type', 'payment_transactions', ['type'], unique=False)
    op.create_index('ix_payment_tx_user_created', 'payment_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('subcategories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subcategories_category', 'subcategories', ['category_id'], unique=False)
    op.create_index(op.f('ix_subcategories_slug'), 'subcategories', ['slug'], unique=True)
    op.create_table('user_consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=20), nullable=False, comment='terms | privacy | cookie | marketing'),
    sa.Column('version', sa.String(length=20), nullable=False, comment="version ของ document เช่น '2026-04-01' หรือ 'v1.2'"),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IPv4/IPv6 ของ user ณ เวลา accept'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_consents_user_type', 'user_consents', ['user_id', 'consent_type'], unique=False)
    op.create_table('user_skills',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skill_id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skill')
    )
    op.create_index('ix_user_skills_skill', 'user_skills', ['skill_id'], unique=False)
    op.create_index('ix_user_skills_user', 'user_skills', ['user_id'], unique=False)
    op.create_table('community_post_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False, comment='URL ของไฟล์ (เก็บใน MinIO / S3)'),
    sa.Column('file_type', sa.String(), nullable=False, comment='ประเภทไฟล์ เช่น image | video | document'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='ลำดับการแสดงผล — น้อยก่อน'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='วันที่สร้างไฟล์แนบ'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_post_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True, comment='สำหรับคอมเมนต์ที่เป็นการตอบกลับ (reply) จะเก็บ ID ของคอมเมนต์ต้นทางที่ถูกตอบกลับ'),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='เนื้อหาคอมเมนต์'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='วันที่สร้างคอมเมนต์'),
    sa.Column('edited_at', sa.DateTime(), nullable=True, comment='วันที่แก้ไข content จริงๆ — set manual ที่ service layer'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='soft delete — ถ้ามีค่าหมายถึงถูกลบแล้ว แต่ replies ยังแสดงอยู่ได้'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['community_post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_post_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False, comment='วันที่ดูโพสต์ล่าสุด — อัปเดตทุกครั้งที่ดู (ใช้กับ logic 30 นาที ที่ service layer)'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_community_post_view')
    )
    op.create_table('kyc_id_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kyc_profile_id', sa.UUID(), nullable=False),
    sa.Column('front_image_file_id', sa.UUID(), nullable=False),
    sa.Column('back_image_file_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['back_image_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['front_image_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['kyc_profile_id'], ['kyc_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_selfies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kyc_profile_id', sa.UUID(), nullable=False),
    sa.Column('image_file_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['kyc_profile_id'], ['kyc_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcategory_skills',
    sa.Column('subcategory_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subcategory_id', 'skill_id'),
    sa.UniqueConstraint('subcategory_id', 'skill_id', name='uq_subcategory_skill')
    )
    op.create_table('community_post_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=True, comment='ถ้า react ที่ comment จะมีค่า, ถ้า react ที่ post จะเป็น null'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reaction_type', sa.Enum('LIKE', 'DISLIKE', name='communityreactiontype'), nullable=False, comment='ประเภทของปฏิกิริยา เช่น like | dislike'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='วันที่สร้างปฏิกิริยา'),
    sa.ForeignKeyConstraint(['comment_id'], ['community_post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'comment_id', 'user_id', name='uq_community_reaction')
    )
    op.create_table('job_skills',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'skill_id'),
    sa.UniqueConstraint('job_id', 'skill_id', name='uq_job_skill')
    )
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True, comment='NULL = deal จาก DM (ไม่ผ่าน job board)'),
    sa.Column('client_id', sa.UUID(), nullable=False, comment='ฝั่งจ้าง — resolve จาก job_type หรือ intent ที่ service layer'),
    sa.Column('freelancer_id', sa.UUID(), nullable=False, comment='ฝั่งรับงาน — resolve จาก job_type หรือ intent ที่ service layer'),
    sa.Column('proposer_id', sa.UUID(), nullable=False, comment='คนที่กด submit proposal — เก็บไว้เพื่อ audit trail'),
    sa.Column('message', sa.Text(), nullable=True, comment='ข้อความแนบ proposal'),
    sa.Column('proposed_budget', sa.Numeric(precision=12, scale=2), nullable=True, comment='งบที่เสนอ — NULL = ยอมรับตาม job budget'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True, comment='เวลาที่อีกฝ่ายตอบรับ/ปฏิเสธ'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposals_client', 'proposals', ['client_id'], unique=False)
    op.create_index('ix_proposals_freelancer', 'proposals', ['freelancer_id'], unique=False)
    op.create_index('ix_proposals_job', 'proposals', ['job_id'], unique=False)
    op.create_index('ix_proposals_status', 'proposals', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True, comment='NULL = private project (ไม่ผ่าน job board)'),
    sa.Column('proposal_id', sa.UUID(), nullable=False, comment='เชื่อมกับ proposal ที่ accepted — ทุก project ต้องมาจาก proposal เสมอ'),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('freelancer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_client', 'projects', ['client_id'], unique=False)
    op.create_index('ix_projects_freelancer', 'projects', ['freelancer_id'], unique=False)
    op.create_index('ix_projects_job', 'projects', ['job_id'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='ลำดับ milestone ใน project'),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('funding_status', sa.String(length=20), nullable=False),
    sa.Column('funded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_milestones_project', 'milestones', ['project_id'], unique=False)
    op.create_index('ix_milestones_status', 'milestones', ['status'], unique=False)
    op.create_table('escrow_holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False, comment='ฝั่งจ้าง — คนที่ชำระเงิน'),
    sa.Column('freelancer_id', sa.UUID(), nullable=False, comment='ฝั่งรับงาน — คนที่จะได้รับเงิน'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('charge_tx_id', sa.UUID(), nullable=False, comment='transaction ที่ client ชำระ (charge succeeded)'),
    sa.Column('release_tx_id', sa.UUID(), nullable=True, comment='transaction ที่ settle (transfer หรือ refund) — NULL ถ้ายัง HELD'),
    sa.Column('held_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('released_by', sa.UUID(), nullable=True, comment='admin UUID ถ้า manual action, NULL ถ้า auto-release'),
    sa.ForeignKeyConstraint(['charge_tx_id'], ['payment_transactions.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['release_tx_id'], ['payment_transactions.id'], ),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('milestone_id', name='uq_escrow_milestone')
    )
    op.create_index('ix_escrow_client', 'escrow_holdings', ['client_id'], unique=False)
    op.create_index('ix_escrow_freelancer', 'escrow_holdings', ['freelancer_id'], unique=False)
    op.create_index('ix_escrow_status', 'escrow_holdings', ['status'], unique=False)
    op.create_table('milestone_submission_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False, comment='submission ที่ไฟล์นี้แนบมา'),
    sa.Column('file_id', sa.UUID(), nullable=False, comment='FK ไปหา files table — เก็บ URL / metadata จริงอยู่ที่นั่น'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='ลำดับการแสดงผล — น้อยก่อน'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['milestone_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submission_files_submission', 'milestone_submission_files', ['submission_id'], unique=False)
    # Add as nullable first to avoid NOT NULL violation on existing rows
    op.add_column('categories', sa.Column('name', sa.String(length=100), nullable=True, comment='ชื่อหมวดหมู่ภาษาอังกฤษ'))
    op.add_column('categories', sa.Column('slug', sa.String(length=100), nullable=True))
    # Backfill existing rows with placeholder values
    op.execute("UPDATE categories SET name = COALESCE(code, id::text), slug = COALESCE(LOWER(REGEXP_REPLACE(code, '[^a-z0-9]', '-', 'g')), id::text) WHERE name IS NULL")
    op.alter_column('categories', 'name', nullable=False)
    op.alter_column('categories', 'slug', nullable=False)
    op.add_column('categories', sa.Column('icon', sa.String(length=200), nullable=True, comment='icon name (lucide) หรือ URL'))
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('categories_code_key'), 'categories', type_='unique')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_column('categories', 'type')
    op.drop_column('categories', 'code')
    op.add_column('chat_rooms', sa.Column('status', sa.String(), nullable=False, server_default='active', comment='active | archived'))
    op.add_column('chat_rooms', sa.Column('job_id', sa.UUID(), nullable=True, comment='Deal Chat: ref Job ที่สร้าง deal (NULL = เริ่มจาก DM)'))
    op.add_column('chat_rooms', sa.Column('proposal_id', sa.UUID(), nullable=True, comment='Deal Chat: 1 deal room = 1 proposal (owner กด open proposal ถึงสร้าง)'))
    op.add_column('chat_rooms', sa.Column('project_id', sa.UUID(), nullable=True, comment='Project Chat: ผูกกับ project หลัง accept deal'))
    op.add_column('chat_rooms', sa.Column('parent_room_id', sa.UUID(), nullable=True, comment='สายพัน DM → Deal → Project: ref ห้องแม่ (history)'))
    op.add_column('chat_rooms', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.alter_column('chat_rooms', 'room_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='dm | deal | project')
    op.alter_column('chat_rooms', 'peer_user_id',
               existing_type=sa.UUID(),
               comment='DM only: peer user ID เพื่อค้นหาห้อง DM ของคู่หน้าได้เร็ว',
               existing_comment='สำหรับห้อง DM, peer_user_id จะเก็บ ID ของผู้ใช้คนอื่นที่เป็นคู่สนทนา (ไม่ใช่เจ้าของห้อง) เพื่อให้ง่ายต่อการค้นหาและจัดการห้อง DM โดยไม่ต้องเชื่อมโยงกับตารางผู้ใช้หลายครั้ง',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'name',
               existing_type=sa.VARCHAR(),
               comment='ชื่อสำหรับ group / Deal / Project chat',
               existing_comment='ชื่อห้องสำหรับแชทกลุ่ม หรือชื่อเล่นสำหรับ DM (ถ้าไม่ระบุจะใช้ชื่อของ peer_user_id สำหรับ DM)',
               existing_nullable=True)
    op.create_index('ix_chat_rooms_parent', 'chat_rooms', ['parent_room_id'], unique=False)
    op.create_index('ix_chat_rooms_project', 'chat_rooms', ['project_id'], unique=False)
    op.create_index('ix_chat_rooms_proposal', 'chat_rooms', ['proposal_id'], unique=False)
    op.create_index('ix_chat_rooms_type_status', 'chat_rooms', ['room_type', 'status'], unique=False)
    op.drop_constraint(op.f('chat_rooms_job_assignment_id_fkey'), 'chat_rooms', type_='foreignkey')
    op.create_foreign_key(None, 'chat_rooms', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'chat_rooms', 'chat_rooms', ['parent_room_id'], ['id'])
    op.create_foreign_key(None, 'chat_rooms', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'chat_rooms', 'proposals', ['proposal_id'], ['id'])
    op.drop_column('chat_rooms', 'job_assignment_id')
    # nullable=True to handle existing dispute rows that had assignment_id (legacy data)
    op.add_column('disputes', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('disputes', sa.Column('reason_detail', sa.Text(), nullable=True, comment='คำอธิบายเพิ่มเติมจากผู้ยื่น'))
    op.add_column('disputes', sa.Column('resolution_note', sa.Text(), nullable=True, comment='หมายเหตุจาก admin'))
    op.alter_column('disputes', 'milestone_id',
               existing_type=sa.UUID(),
               comment='NULL = dispute ระดับ project ทั้งหมด',
               existing_nullable=True)
    # Truncate existing reason values that may exceed 50 chars before type change
    op.execute("UPDATE disputes SET reason = LEFT(reason, 50) WHERE LENGTH(reason) > 50")
    op.alter_column('disputes', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               comment='DisputeReason enum',
               existing_nullable=False)
    op.alter_column('disputes', 'resolution',
               existing_type=sa.VARCHAR(),
               comment='DisputeResolution enum — set เมื่อ admin ตัดสิน',
               existing_nullable=True)
    op.create_index('ix_disputes_milestone', 'disputes', ['milestone_id'], unique=False)
    op.create_index('ix_disputes_milestone_open', 'disputes', ['milestone_id', 'status'], unique=False)
    op.create_index('ix_disputes_project', 'disputes', ['project_id'], unique=False)
    op.create_index('ix_disputes_status', 'disputes', ['status'], unique=False)
    op.drop_constraint(op.f('disputes_assignment_id_fkey'), 'disputes', type_='foreignkey')
    op.drop_constraint(op.f('disputes_milestone_id_fkey'), 'disputes', type_='foreignkey')
    # Clear orphaned milestone_ids (old job_milestones no longer exist) + stale user refs
    op.execute("UPDATE disputes SET milestone_id = NULL")
    op.execute("UPDATE disputes SET raised_by = NULL WHERE raised_by NOT IN (SELECT id FROM users)")
    op.execute("UPDATE disputes SET resolved_by = NULL WHERE resolved_by IS NOT NULL AND resolved_by NOT IN (SELECT id FROM users)")
    op.create_foreign_key(None, 'disputes', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'disputes', 'users', ['resolved_by'], ['id'])
    op.create_foreign_key(None, 'disputes', 'users', ['raised_by'], ['id'])
    op.create_foreign_key(None, 'disputes', 'milestones', ['milestone_id'], ['id'])
    op.drop_column('disputes', 'assignment_id')
    op.add_column('evidences', sa.Column('file_id', sa.UUID(), nullable=True))
    op.alter_column('evidences', 'type',
               existing_type=sa.VARCHAR(),
               comment='text | file',
               existing_nullable=False)
    op.create_foreign_key(None, 'evidences', 'files', ['file_id'], ['id'])
    # Clear evidences with stale submitted_by user refs
    op.execute("UPDATE evidences SET submitted_by = NULL WHERE submitted_by IS NOT NULL AND submitted_by NOT IN (SELECT id FROM users)")
    op.create_foreign_key(None, 'evidences', 'users', ['submitted_by'], ['id'])
    op.add_column('jobs', sa.Column('job_type', sa.String(length=20), nullable=False, server_default='hire', comment='hire = client หาคน | service = freelancer เสนอบริการ'))
    op.add_column('jobs', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('subcategory_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('delivery_date', sa.Date(), nullable=True, comment='วันที่ต้องการส่งมอบงาน (nullable)'))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('jobs', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               comment='URL รูปประกอบ/ตัวอย่างงาน')
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='วันหมดอายุการรับ proposal',
               existing_nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('ix_jobs_category', 'jobs', ['category_id'], unique=False)
    op.create_index('ix_jobs_expires_at', 'jobs', ['expires_at'], unique=False)
    op.create_index('ix_jobs_owner', 'jobs', ['owner_id'], unique=False)
    op.create_index('ix_jobs_status_type', 'jobs', ['status', 'job_type'], unique=False)
    op.create_index('ix_jobs_subcategory', 'jobs', ['subcategory_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'subcategories', ['subcategory_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'categories', ['category_id'], ['id'])
    op.drop_column('jobs', 'currency')
    op.drop_column('jobs', 'deadline_date')
    op.alter_column('milestone_submissions', 'milestone_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='milestone ที่ส่งงานนี้เข้าไป')
    op.alter_column('milestone_submissions', 'submitted_by',
               existing_type=sa.UUID(),
               nullable=False,
               comment='freelancer ที่กด submit งาน')
    op.alter_column('milestone_submissions', 'revision_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='รอบที่ส่ง — เพิ่มขึ้นทุกครั้งที่ client reject แล้ว freelancer ส่งใหม่')
    op.alter_column('milestone_submissions', 'message',
               existing_type=sa.TEXT(),
               comment='ข้อความอธิบายงานที่ส่ง เช่น สิ่งที่ทำ, link, หมายเหตุ',
               existing_nullable=True)
    op.alter_column('milestone_submissions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='pending = รอ client ตรวจ | approved = client อนุมัติ | rejected = client reject')
    op.alter_column('milestone_submissions', 'auto_release_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='True = client ไม่ตรวจงานเกิน SLA_CLIENT_REVIEW_DAYS → admin สามารถ force approve ได้')
    op.alter_column('milestone_submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment='เวลาที่ freelancer กด submit — ใช้คำนวณ SLA')
    op.alter_column('milestone_submissions', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='เวลาที่ client อนุมัติหรือ reject — NULL = ยังรอการตรวจ',
               existing_nullable=True)
    op.drop_constraint(op.f('milestone_submissions_milestone_id_fkey'), 'milestone_submissions', type_='foreignkey')
    # Clear milestone_submissions with stale milestone_ids (old job_milestones no longer in milestones table)
    op.execute("DELETE FROM milestone_submissions WHERE milestone_id NOT IN (SELECT id FROM milestones)")
    op.create_foreign_key(None, 'milestone_submissions', 'milestones', ['milestone_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'milestone_submissions', 'users', ['submitted_by'], ['id'])
    op.drop_column('milestone_submissions', 'attachments')
    # nullable=True to handle existing review rows that had assignment_id (legacy data)
    op.add_column('reviews', sa.Column('project_id', sa.UUID(), nullable=True, comment='Project ที่ review นี้สัมพันธ์อยู่ด้วย'))
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               comment='1–5',
               existing_nullable=False)
    op.create_index('ix_reviews_project', 'reviews', ['project_id'], unique=False)
    op.create_index('ix_reviews_reviewee', 'reviews', ['reviewee_id'], unique=False)
    op.drop_constraint(op.f('reviews_assignment_id_fkey'), 'reviews', type_='foreignkey')
    # reviews.project_id is nullable — existing reviews will have NULL project_id (legacy data)
    op.create_foreign_key(None, 'reviews', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'users', ['reviewee_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'users', ['reviewer_id'], ['id'])
    op.drop_column('reviews', 'assignment_id')
    op.alter_column('user_freelance_skills', 'hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_comment='อัตราค่าบริการต่อชั่วโมง (หน่วย: บาท)',
               existing_nullable=True)
    op.drop_column('user_freelance_skills', 'skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_freelance_skills', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment="รายการทักษะ เช่น ['Python', 'React']"))
    op.alter_column('user_freelance_skills', 'hourly_rate',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='อัตราค่าบริการต่อชั่วโมง (หน่วย: บาท)',
               existing_nullable=True)
    op.add_column('reviews', sa.Column('assignment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_assignment_id_fkey'), 'reviews', 'job_assignments', ['assignment_id'], ['id'])
    op.drop_index('ix_reviews_reviewee', table_name='reviews')
    op.drop_index('ix_reviews_project', table_name='reviews')
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='1–5',
               existing_nullable=False)
    op.drop_column('reviews', 'project_id')
    op.add_column('milestone_submissions', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'milestone_submissions', type_='foreignkey')
    op.drop_constraint(None, 'milestone_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('milestone_submissions_milestone_id_fkey'), 'milestone_submissions', 'job_milestones', ['milestone_id'], ['id'])
    op.alter_column('milestone_submissions', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='เวลาที่ client อนุมัติหรือ reject — NULL = ยังรอการตรวจ',
               existing_nullable=True)
    op.alter_column('milestone_submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='เวลาที่ freelancer กด submit — ใช้คำนวณ SLA')
    op.alter_column('milestone_submissions', 'auto_release_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='True = client ไม่ตรวจงานเกิน SLA_CLIENT_REVIEW_DAYS → admin สามารถ force approve ได้')
    op.alter_column('milestone_submissions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='pending = รอ client ตรวจ | approved = client อนุมัติ | rejected = client reject')
    op.alter_column('milestone_submissions', 'message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='ข้อความอธิบายงานที่ส่ง เช่น สิ่งที่ทำ, link, หมายเหตุ',
               existing_nullable=True)
    op.alter_column('milestone_submissions', 'revision_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='รอบที่ส่ง — เพิ่มขึ้นทุกครั้งที่ client reject แล้ว freelancer ส่งใหม่')
    op.alter_column('milestone_submissions', 'submitted_by',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='freelancer ที่กด submit งาน')
    op.alter_column('milestone_submissions', 'milestone_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='milestone ที่ส่งงานนี้เข้าไป')
    op.add_column('jobs', sa.Column('deadline_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index('ix_jobs_subcategory', table_name='jobs')
    op.drop_index('ix_jobs_status_type', table_name='jobs')
    op.drop_index('ix_jobs_owner', table_name='jobs')
    op.drop_index('ix_jobs_expires_at', table_name='jobs')
    op.drop_index('ix_jobs_category', table_name='jobs')
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jobs', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='วันหมดอายุการรับ proposal',
               existing_nullable=True)
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment=None,
               existing_comment='URL รูปประกอบ/ตัวอย่างงาน')
    op.alter_column('jobs', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'delivery_date')
    op.drop_column('jobs', 'subcategory_id')
    op.drop_column('jobs', 'category_id')
    op.drop_column('jobs', 'job_type')
    op.drop_constraint(None, 'evidences', type_='foreignkey')
    op.drop_constraint(None, 'evidences', type_='foreignkey')
    op.alter_column('evidences', 'type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='text | file',
               existing_nullable=False)
    op.drop_column('evidences', 'file_id')
    op.add_column('disputes', sa.Column('assignment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.create_foreign_key(op.f('disputes_milestone_id_fkey'), 'disputes', 'job_milestones', ['milestone_id'], ['id'])
    op.create_foreign_key(op.f('disputes_assignment_id_fkey'), 'disputes', 'job_assignments', ['assignment_id'], ['id'])
    op.drop_index('ix_disputes_status', table_name='disputes')
    op.drop_index('ix_disputes_project', table_name='disputes')
    op.drop_index('ix_disputes_milestone_open', table_name='disputes')
    op.drop_index('ix_disputes_milestone', table_name='disputes')
    op.alter_column('disputes', 'resolution',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='DisputeResolution enum — set เมื่อ admin ตัดสิน',
               existing_nullable=True)
    op.alter_column('disputes', 'reason',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='DisputeReason enum',
               existing_nullable=False)
    op.alter_column('disputes', 'milestone_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='NULL = dispute ระดับ project ทั้งหมด',
               existing_nullable=True)
    op.drop_column('disputes', 'resolution_note')
    op.drop_column('disputes', 'reason_detail')
    op.drop_column('disputes', 'project_id')
    op.add_column('chat_rooms', sa.Column('job_assignment_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.create_foreign_key(op.f('chat_rooms_job_assignment_id_fkey'), 'chat_rooms', 'job_assignments', ['job_assignment_id'], ['id'])
    op.drop_index('ix_chat_rooms_type_status', table_name='chat_rooms')
    op.drop_index('ix_chat_rooms_proposal', table_name='chat_rooms')
    op.drop_index('ix_chat_rooms_project', table_name='chat_rooms')
    op.drop_index('ix_chat_rooms_parent', table_name='chat_rooms')
    op.alter_column('chat_rooms', 'name',
               existing_type=sa.VARCHAR(),
               comment='ชื่อห้องสำหรับแชทกลุ่ม หรือชื่อเล่นสำหรับ DM (ถ้าไม่ระบุจะใช้ชื่อของ peer_user_id สำหรับ DM)',
               existing_comment='ชื่อสำหรับ group / Deal / Project chat',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'peer_user_id',
               existing_type=sa.UUID(),
               comment='สำหรับห้อง DM, peer_user_id จะเก็บ ID ของผู้ใช้คนอื่นที่เป็นคู่สนทนา (ไม่ใช่เจ้าของห้อง) เพื่อให้ง่ายต่อการค้นหาและจัดการห้อง DM โดยไม่ต้องเชื่อมโยงกับตารางผู้ใช้หลายครั้ง',
               existing_comment='DM only: peer user ID เพื่อค้นหาห้อง DM ของคู่หน้าได้เร็ว',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'room_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='dm | deal | project')
    op.drop_column('chat_rooms', 'updated_at')
    op.drop_column('chat_rooms', 'parent_room_id')
    op.drop_column('chat_rooms', 'project_id')
    op.drop_column('chat_rooms', 'proposal_id')
    op.drop_column('chat_rooms', 'job_id')
    op.drop_column('chat_rooms', 'status')
    op.add_column('categories', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_unique_constraint(op.f('categories_code_key'), 'categories', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('categories', 'icon')
    op.drop_column('categories', 'slug')
    op.drop_column('categories', 'name')
    op.drop_index('ix_submission_files_submission', table_name='milestone_submission_files')
    op.drop_table('milestone_submission_files')
    op.drop_index('ix_escrow_status', table_name='escrow_holdings')
    op.drop_index('ix_escrow_freelancer', table_name='escrow_holdings')
    op.drop_index('ix_escrow_client', table_name='escrow_holdings')
    op.drop_table('escrow_holdings')
    op.drop_index('ix_milestones_status', table_name='milestones')
    op.drop_index('ix_milestones_project', table_name='milestones')
    op.drop_table('milestones')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_job', table_name='projects')
    op.drop_index('ix_projects_freelancer', table_name='projects')
    op.drop_index('ix_projects_client', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_proposals_status', table_name='proposals')
    op.drop_index('ix_proposals_job', table_name='proposals')
    op.drop_index('ix_proposals_freelancer', table_name='proposals')
    op.drop_index('ix_proposals_client', table_name='proposals')
    op.drop_table('proposals')
    op.drop_table('job_skills')
    op.drop_table('community_post_reactions')
    op.drop_table('subcategory_skills')
    op.drop_table('kyc_selfies')
    op.drop_table('kyc_id_cards')
    op.drop_table('community_post_views')
    op.drop_table('community_post_comments')
    op.drop_table('community_post_attachments')
    op.drop_index('ix_user_skills_user', table_name='user_skills')
    op.drop_index('ix_user_skills_skill', table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index('ix_user_consents_user_type', table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_subcategories_slug'), table_name='subcategories')
    op.drop_index('ix_subcategories_category', table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_index('ix_payment_tx_user_created', table_name='payment_transactions')
    op.drop_index('ix_payment_tx_type', table_name='payment_transactions')
    op.drop_index('ix_payment_tx_status', table_name='payment_transactions')
    op.drop_index('ix_payment_tx_reference', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index('ix_notification_settings_user', table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_index('ix_kyc_profiles_status', table_name='kyc_profiles')
    op.drop_table('kyc_profiles')
    op.drop_table('file_access_logs')
    op.drop_index('ix_community_posts_created_at', table_name='community_posts')
    op.drop_index('ix_community_posts_category', table_name='community_posts')
    op.drop_index('ix_community_posts_author_id', table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index('ix_audit_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_activity_subject', table_name='activity_logs')
    op.drop_index('ix_activity_event', table_name='activity_logs')
    op.drop_index('ix_activity_created', table_name='activity_logs')
    op.drop_index('ix_activity_actor', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_table('skills')
    op.drop_table('files')
    # ### end Alembic commands ###
