"""add_display_name_phone_to_users

Revision ID: 20fb29170162
Revises: ee1c2dcb6fc0
Create Date: 2026-04-02 06:00:19.735071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20fb29170162'
down_revision: Union[str, Sequence[str], None] = 'ee1c2dcb6fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
