"""add_payment_customers_and_methods

Revision ID: 2de8a4f0b470
Revises: 9e73f183cc35
Create Date: 2026-04-05 16:02:12.077827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2de8a4f0b470'
down_revision: Union[str, Sequence[str], None] = '9e73f183cc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gateway_provider', sa.String(length=20), nullable=False, comment='omise | stripe | promptpay | manual'),
    sa.Column('gateway_customer_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_provider', 'gateway_customer_id', name='uq_payment_customer_gateway'),
    sa.UniqueConstraint('user_id', name='uq_payment_customer_user')
    )
    op.create_index('ix_payment_customer_provider', 'payment_customers', ['gateway_provider'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_customer_id', sa.UUID(), nullable=False),
    sa.Column('gateway_provider', sa.String(length=20), nullable=False, comment='omise | stripe | promptpay | manual'),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('gateway_payment_method_id', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('exp_month', sa.Integer(), nullable=True),
    sa.Column('exp_year', sa.Integer(), nullable=True),
    sa.Column('holder_name', sa.String(length=255), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('reusable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False, comment='active | inactive | expired | deleted'),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_customer_id'], ['payment_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_provider', 'gateway_payment_method_id', name='uq_payment_method_gateway_ref')
    )
    op.create_index('ix_payment_methods_default', 'payment_methods', ['user_id', 'is_default'], unique=False)
    op.create_index('ix_payment_methods_status', 'payment_methods', ['status'], unique=False)
    op.create_index('ix_payment_methods_user', 'payment_methods', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_methods_user', table_name='payment_methods')
    op.drop_index('ix_payment_methods_status', table_name='payment_methods')
    op.drop_index('ix_payment_methods_default', table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index('ix_payment_customer_provider', table_name='payment_customers')
    op.drop_table('payment_customers')
    # ### end Alembic commands ###
