"""add_user_freelance_skill_and_portfolio_tables

Revision ID: 49d681dc59dd
Revises: 20fb29170162
Create Date: 2026-04-02 11:59:08.362609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49d681dc59dd'
down_revision: Union[str, Sequence[str], None] = '20fb29170162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_freelance_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tagline', sa.String(), nullable=True, comment='tagline สั้นๆ แสดงความเชี่ยวชาญหรือจุดเด่นของ'),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="รายการทักษะของผู้ใช้ เช่น ['Python', 'React', ...]"),
    sa.Column('hourly_rate', sa.Float(), nullable=True, comment='อัตราค่าบริการต่อชั่วโมงของผู้ใช้'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='freelancer opt-in to appear in public listings'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_freelance_skills_user_id'), 'user_freelance_skills', ['user_id'], unique=False)
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('kyc_status', sa.String(), nullable=True))
    # Drop old columns that moved into user_freelance_skills
    op.drop_column('users', 'is_public')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'hourly_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore dropped columns
    op.add_column('users', sa.Column('hourly_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'kyc_status')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'deleted_at')
    op.drop_index(op.f('ix_user_freelance_skills_user_id'), table_name='user_freelance_skills')
    op.drop_table('user_freelance_skills')
    # ### end Alembic commands ###
