"""align_remaining_comments

Revision ID: 54b88cecbf4c
Revises: 12c9a81160b7
Create Date: 2026-04-05 12:42:55.859332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54b88cecbf4c'
down_revision: Union[str, Sequence[str], None] = '12c9a81160b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'actor_id',
               existing_type=sa.UUID(),
               comment='ผู้ทำ action — NULL = system/automated',
               existing_nullable=True)
    op.alter_column('activity_logs', 'event',
               existing_type=sa.VARCHAR(length=60),
               comment='ActivityEvent enum value',
               existing_nullable=False)
    op.alter_column('activity_logs', 'subject_type',
               existing_type=sa.VARCHAR(length=40),
               comment='entity ที่เกิด event: job | proposal | project | milestone | dispute',
               existing_nullable=True)
    op.alter_column('activity_logs', 'subject_id',
               existing_type=sa.UUID(),
               comment='id ของ entity นั้น',
               existing_nullable=True)
    op.alter_column('activity_logs', 'snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='ข้อมูล denormalized สำหรับแสดงผล feed โดยไม่ต้อง JOIN เช่น {title, amount, username}',
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               comment='ผู้ทำ action — NULL = system/automated',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=60),
               comment='AuditAction enum value',
               existing_nullable=False)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=40),
               comment='user | kyc | payment | dispute ฯลฯ',
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='ค่าเดิมก่อน action — สำหรับ change tracking',
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='ค่าใหม่หลัง action',
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               comment='IP ของ request',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               comment='Browser/client ที่ใช้',
               existing_nullable=True)
    op.alter_column('audit_logs', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='context เพิ่มเติม สำหรับ debug',
               existing_nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='ชื่อหมวดหมู่ภาษาอังกฤษ',
               existing_nullable=False)
    op.alter_column('categories', 'icon',
               existing_type=sa.VARCHAR(length=200),
               comment='icon name (lucide) หรือ URL',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'status',
               existing_type=sa.VARCHAR(),
               comment='active | archived',
               existing_nullable=False)
    op.alter_column('chat_rooms', 'job_id',
               existing_type=sa.UUID(),
               comment='Deal Chat: ref Job ที่สร้าง deal (NULL = เริ่มจาก DM)',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'proposal_id',
               existing_type=sa.UUID(),
               comment='Deal Chat: 1 deal room = 1 proposal (owner กด open proposal ถึงสร้าง)',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'project_id',
               existing_type=sa.UUID(),
               comment='Project Chat: ผูกกับ project หลัง accept deal',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'parent_room_id',
               existing_type=sa.UUID(),
               comment='สายพัน DM → Deal → Project: ref ห้องแม่ (history)',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'peer_user_id',
               existing_type=sa.UUID(),
               comment='DM only: peer user ID เพื่อค้นหาห้อง DM ของคู่หน้าได้เร็ว',
               existing_comment='DM only: peer user ID',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'name',
               existing_type=sa.VARCHAR(),
               comment='ชื่อสำหรับ group / Deal / Project chat',
               existing_comment='Name for deal or project chat',
               existing_nullable=True)
    op.alter_column('disputes', 'milestone_id',
               existing_type=sa.UUID(),
               comment='NULL = dispute ระดับ project ทั้งหมด',
               existing_nullable=True)
    op.alter_column('disputes', 'reason',
               existing_type=sa.VARCHAR(length=50),
               comment='DisputeReason enum',
               existing_nullable=False)
    op.alter_column('disputes', 'reason_detail',
               existing_type=sa.TEXT(),
               comment='คำอธิบายเพิ่มเติมจากผู้ยื่น',
               existing_nullable=True)
    op.alter_column('disputes', 'resolution',
               existing_type=sa.VARCHAR(length=30),
               comment='DisputeResolution enum — set เมื่อ admin ตัดสิน',
               existing_nullable=True)
    op.alter_column('disputes', 'resolution_note',
               existing_type=sa.TEXT(),
               comment='หมายเหตุจาก admin',
               existing_nullable=True)
    op.alter_column('evidences', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='text | file',
               existing_nullable=False)
    op.alter_column('jobs', 'job_type',
               existing_type=sa.VARCHAR(length=20),
               comment='hire = client หาคน | service = freelancer เสนอบริการ',
               existing_nullable=False)
    op.alter_column('jobs', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='URL รูปประกอบ/ตัวอย่างงาน',
               existing_nullable=False)
    op.alter_column('jobs', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='วันหมดอายุการรับ proposal',
               existing_nullable=True)
    op.alter_column('jobs', 'delivery_date',
               existing_type=sa.DATE(),
               comment='วันที่ต้องการส่งมอบงาน (nullable)',
               existing_nullable=True)
    op.alter_column('kyc_profiles', 'status',
               existing_type=sa.VARCHAR(),
               comment='pending | verified | rejected',
               existing_nullable=False)
    op.alter_column('kyc_profiles', 'reviewed_by',
               existing_type=sa.UUID(),
               comment='Admin user ที่ตรวจสอบ',
               existing_nullable=True)
    op.alter_column('kyc_profiles', 'review_note',
               existing_type=sa.TEXT(),
               comment='เหตุผลที่ reject หรือ note จาก admin',
               existing_nullable=True)
    op.alter_column('notification_settings', 'notification_type',
               existing_type=sa.VARCHAR(),
               comment='NotificationType enum value',
               existing_nullable=False)
    op.alter_column('projects', 'job_id',
               existing_type=sa.UUID(),
               comment='NULL for direct-message deals',
               existing_nullable=True)
    op.alter_column('projects', 'proposal_id',
               existing_type=sa.UUID(),
               comment='Accepted proposal that created this project',
               existing_nullable=False)
    op.alter_column('proposals', 'job_id',
               existing_type=sa.UUID(),
               comment='NULL = deal จาก DM (ไม่ผ่าน job board)',
               existing_nullable=True)
    op.alter_column('proposals', 'client_id',
               existing_type=sa.UUID(),
               comment='ฝั่งจ้าง — resolve จาก job_type หรือ intent ที่ service layer',
               existing_nullable=False)
    op.alter_column('proposals', 'freelancer_id',
               existing_type=sa.UUID(),
               comment='ฝั่งรับงาน — resolve จาก job_type หรือ intent ที่ service layer',
               existing_nullable=False)
    op.alter_column('proposals', 'proposer_id',
               existing_type=sa.UUID(),
               comment='คนที่กด submit proposal — เก็บไว้เพื่อ audit trail',
               existing_nullable=False)
    op.alter_column('proposals', 'message',
               existing_type=sa.TEXT(),
               comment='ข้อความแนบ proposal',
               existing_nullable=True)
    op.alter_column('proposals', 'proposed_budget',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='งบที่เสนอ — NULL = ยอมรับตาม job budget',
               existing_nullable=True)
    op.alter_column('proposals', 'responded_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='เวลาที่อีกฝ่ายตอบรับ/ปฏิเสธ',
               existing_nullable=True)
    op.alter_column('reviews', 'project_id',
               existing_type=sa.UUID(),
               comment='Project ที่ review นี้สัมพันธ์อยู่ด้วย',
               existing_nullable=False)
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               comment='1–5',
               existing_nullable=False)
    op.alter_column('user_consents', 'consent_type',
               existing_type=sa.VARCHAR(length=20),
               comment='terms | privacy | cookie | marketing',
               existing_nullable=False)
    op.alter_column('user_consents', 'version',
               existing_type=sa.VARCHAR(length=20),
               comment='Accepted document version',
               existing_nullable=False)
    op.alter_column('user_consents', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='IPv4/IPv6 at acceptance time',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_consents', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='IPv4/IPv6 at acceptance time',
               existing_nullable=True)
    op.alter_column('user_consents', 'version',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Accepted document version',
               existing_nullable=False)
    op.alter_column('user_consents', 'consent_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='terms | privacy | cookie | marketing',
               existing_nullable=False)
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='1–5',
               existing_nullable=False)
    op.alter_column('reviews', 'project_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Project ที่ review นี้สัมพันธ์อยู่ด้วย',
               existing_nullable=False)
    op.alter_column('proposals', 'responded_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='เวลาที่อีกฝ่ายตอบรับ/ปฏิเสธ',
               existing_nullable=True)
    op.alter_column('proposals', 'proposed_budget',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='งบที่เสนอ — NULL = ยอมรับตาม job budget',
               existing_nullable=True)
    op.alter_column('proposals', 'message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='ข้อความแนบ proposal',
               existing_nullable=True)
    op.alter_column('proposals', 'proposer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='คนที่กด submit proposal — เก็บไว้เพื่อ audit trail',
               existing_nullable=False)
    op.alter_column('proposals', 'freelancer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ฝั่งรับงาน — resolve จาก job_type หรือ intent ที่ service layer',
               existing_nullable=False)
    op.alter_column('proposals', 'client_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ฝั่งจ้าง — resolve จาก job_type หรือ intent ที่ service layer',
               existing_nullable=False)
    op.alter_column('proposals', 'job_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='NULL = deal จาก DM (ไม่ผ่าน job board)',
               existing_nullable=True)
    op.alter_column('projects', 'proposal_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Accepted proposal that created this project',
               existing_nullable=False)
    op.alter_column('projects', 'job_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='NULL for direct-message deals',
               existing_nullable=True)
    op.alter_column('notification_settings', 'notification_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='NotificationType enum value',
               existing_nullable=False)
    op.alter_column('kyc_profiles', 'review_note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='เหตุผลที่ reject หรือ note จาก admin',
               existing_nullable=True)
    op.alter_column('kyc_profiles', 'reviewed_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Admin user ที่ตรวจสอบ',
               existing_nullable=True)
    op.alter_column('kyc_profiles', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='pending | verified | rejected',
               existing_nullable=False)
    op.alter_column('jobs', 'delivery_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='วันที่ต้องการส่งมอบงาน (nullable)',
               existing_nullable=True)
    op.alter_column('jobs', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='วันหมดอายุการรับ proposal',
               existing_nullable=True)
    op.alter_column('jobs', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='URL รูปประกอบ/ตัวอย่างงาน',
               existing_nullable=False)
    op.alter_column('jobs', 'job_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='hire = client หาคน | service = freelancer เสนอบริการ',
               existing_nullable=False)
    op.alter_column('evidences', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='text | file',
               existing_nullable=False)
    op.alter_column('disputes', 'resolution_note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='หมายเหตุจาก admin',
               existing_nullable=True)
    op.alter_column('disputes', 'resolution',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='DisputeResolution enum — set เมื่อ admin ตัดสิน',
               existing_nullable=True)
    op.alter_column('disputes', 'reason_detail',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='คำอธิบายเพิ่มเติมจากผู้ยื่น',
               existing_nullable=True)
    op.alter_column('disputes', 'reason',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='DisputeReason enum',
               existing_nullable=False)
    op.alter_column('disputes', 'milestone_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='NULL = dispute ระดับ project ทั้งหมด',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'name',
               existing_type=sa.VARCHAR(),
               comment='Name for deal or project chat',
               existing_comment='ชื่อสำหรับ group / Deal / Project chat',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'peer_user_id',
               existing_type=sa.UUID(),
               comment='DM only: peer user ID',
               existing_comment='DM only: peer user ID เพื่อค้นหาห้อง DM ของคู่หน้าได้เร็ว',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'parent_room_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='สายพัน DM → Deal → Project: ref ห้องแม่ (history)',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'project_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Project Chat: ผูกกับ project หลัง accept deal',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'proposal_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Deal Chat: 1 deal room = 1 proposal (owner กด open proposal ถึงสร้าง)',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'job_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Deal Chat: ref Job ที่สร้าง deal (NULL = เริ่มจาก DM)',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='active | archived',
               existing_nullable=False)
    op.alter_column('categories', 'icon',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='icon name (lucide) หรือ URL',
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='ชื่อหมวดหมู่ภาษาอังกฤษ',
               existing_nullable=False)
    op.alter_column('audit_logs', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='context เพิ่มเติม สำหรับ debug',
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Browser/client ที่ใช้',
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               comment=None,
               existing_comment='IP ของ request',
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='ค่าใหม่หลัง action',
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='ค่าเดิมก่อน action — สำหรับ change tracking',
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='user | kyc | payment | dispute ฯลฯ',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=60),
               comment=None,
               existing_comment='AuditAction enum value',
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ผู้ทำ action — NULL = system/automated',
               existing_nullable=True)
    op.alter_column('activity_logs', 'snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='ข้อมูล denormalized สำหรับแสดงผล feed โดยไม่ต้อง JOIN เช่น {title, amount, username}',
               existing_nullable=False)
    op.alter_column('activity_logs', 'subject_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='id ของ entity นั้น',
               existing_nullable=True)
    op.alter_column('activity_logs', 'subject_type',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='entity ที่เกิด event: job | proposal | project | milestone | dispute',
               existing_nullable=True)
    op.alter_column('activity_logs', 'event',
               existing_type=sa.VARCHAR(length=60),
               comment=None,
               existing_comment='ActivityEvent enum value',
               existing_nullable=False)
    op.alter_column('activity_logs', 'actor_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ผู้ทำ action — NULL = system/automated',
               existing_nullable=True)
    # ### end Alembic commands ###
