"""

Revision ID: 86b32bcd5e53
Revises: 9219be0b6291
Create Date: 2026-04-02 14:50:45.368941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b32bcd5e53'
down_revision: Union[str, Sequence[str], None] = '9219be0b6291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('freelancer_portfolios_user_id_key'), 'freelancer_portfolios', type_='unique')
    op.create_index(op.f('ix_freelancer_portfolios_user_id'), 'freelancer_portfolios', ['user_id'], unique=True)
    op.drop_index(op.f('ix_portfolio_comments_portfolio_item_id'), table_name='portfolio_comments')
    op.drop_index(op.f('ix_portfolio_comments_user_id'), table_name='portfolio_comments')
    op.add_column('portfolio_files', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_portfolio_files_portfolio_id'), 'portfolio_files', ['portfolio_id'], unique=False)
    op.drop_index(op.f('ix_portfolio_items_category'), table_name='portfolio_items')
    op.drop_index(op.f('ix_portfolio_likes_portfolio_item_id'), table_name='portfolio_likes')
    op.drop_index(op.f('ix_portfolio_likes_user_id'), table_name='portfolio_likes')
    op.alter_column('users', 'email',
               server_default="test@example.com",
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='อีเมลของผู้ใช้ และติดต่อ')
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               comment='active | inactive | banned',
               existing_nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='ชื่อจริงของผู้ใช้')
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               comment='นามสกุลของผู้ใช้',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               comment='URL ของรูปโปรไฟล์ผู้ใช้',
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               comment='ข้อมูลอธิบายตัวตน',
               existing_nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               comment='ชื่อที่แสดงบนแพลตฟอร์ม (ถ้าไม่ระบุจะใช้ชื่อจริง)',
               existing_nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ชื่อที่แสดงบนแพลตฟอร์ม (ถ้าไม่ระบุจะใช้ชื่อจริง)',
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='ข้อมูลอธิบายตัวตน',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='URL ของรูปโปรไฟล์ผู้ใช้',
               existing_nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='นามสกุลของผู้ใช้',
               existing_nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='ชื่อจริงของผู้ใช้')
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='active | inactive | banned',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='อีเมลของผู้ใช้ และติดต่อ')
    op.create_index(op.f('ix_portfolio_likes_user_id'), 'portfolio_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_portfolio_likes_portfolio_item_id'), 'portfolio_likes', ['portfolio_item_id'], unique=False)
    op.create_index(op.f('ix_portfolio_items_category'), 'portfolio_items', ['category'], unique=False)
    op.drop_index(op.f('ix_portfolio_files_portfolio_id'), table_name='portfolio_files')
    op.drop_column('portfolio_files', 'updated_at')
    op.create_index(op.f('ix_portfolio_comments_user_id'), 'portfolio_comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_portfolio_comments_portfolio_item_id'), 'portfolio_comments', ['portfolio_item_id'], unique=False)
    op.drop_index(op.f('ix_freelancer_portfolios_user_id'), table_name='freelancer_portfolios')
    op.create_unique_constraint(op.f('freelancer_portfolios_user_id_key'), 'freelancer_portfolios', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
