"""align_payment_models_for_omise_and_escrow

Revision ID: 9e73f183cc35
Revises: 8f2c7de1a4b3
Create Date: 2026-04-05 15:46:28.977660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e73f183cc35'
down_revision: Union[str, Sequence[str], None] = '8f2c7de1a4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escrow_holdings', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('escrow_holdings', sa.Column('payout_account_id', sa.UUID(), nullable=True, comment='Selected payout account at the time of release planning'))
    op.add_column('escrow_holdings', sa.Column('omise_recipient_ref_id', sa.UUID(), nullable=True, comment='Resolved Omise recipient used for payout'))
    op.add_column('escrow_holdings', sa.Column('platform_fee_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('escrow_holdings', sa.Column('net_payout_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('escrow_holdings', sa.Column('currency', sa.String(length=3), nullable=False, server_default=sa.text("'THB'")))
    op.add_column('escrow_holdings', sa.Column('auto_release_at', sa.DateTime(), nullable=True))
    op.add_column('escrow_holdings', sa.Column('last_status_changed_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.execute("""
        UPDATE escrow_holdings AS eh
        SET
            project_id = m.project_id,
            platform_fee_amount = COALESCE(eh.platform_fee_amount, 0),
            net_payout_amount = COALESCE(NULLIF(eh.net_payout_amount, 0), eh.amount),
            currency = COALESCE(eh.currency, 'THB'),
            last_status_changed_at = COALESCE(eh.released_at, eh.held_at, NOW())
        FROM milestones AS m
        WHERE eh.milestone_id = m.id
    """)
    op.alter_column('escrow_holdings', 'client_id',
               existing_type=sa.UUID(),
               comment='Client funding the milestone',
               existing_comment='ฝั่งจ้าง — คนที่ชำระเงิน',
               existing_nullable=False)
    op.alter_column('escrow_holdings', 'freelancer_id',
               existing_type=sa.UUID(),
               comment='Freelancer receiving the payout after release',
               existing_comment='ฝั่งรับงาน — คนที่จะได้รับเงิน',
               existing_nullable=False)
    op.alter_column('escrow_holdings', 'charge_tx_id',
               existing_type=sa.UUID(),
               comment='Funding transaction from the client',
               existing_comment='transaction ที่ client ชำระ (charge succeeded)',
               existing_nullable=False)
    op.alter_column('escrow_holdings', 'release_tx_id',
               existing_type=sa.UUID(),
               comment='Settlement transaction for transfer or refund',
               existing_comment='transaction ที่ settle (transfer หรือ refund) — NULL ถ้ายัง HELD',
               existing_nullable=True)
    op.alter_column('escrow_holdings', 'released_by',
               existing_type=sa.UUID(),
               comment='Admin user id for manual release or refund',
               existing_comment='admin UUID ถ้า manual action, NULL ถ้า auto-release',
               existing_nullable=True)
    op.alter_column('escrow_holdings', 'platform_fee_amount', server_default=None)
    op.alter_column('escrow_holdings', 'net_payout_amount', server_default=None)
    op.alter_column('escrow_holdings', 'currency', server_default=None)
    op.alter_column('escrow_holdings', 'last_status_changed_at', server_default=None)
    op.create_index('ix_escrow_project', 'escrow_holdings', ['project_id'], unique=False)
    op.create_foreign_key('fk_escrow_holdings_omise_recipient_ref_id', 'escrow_holdings', 'omise_recipients', ['omise_recipient_ref_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_escrow_holdings_payout_account_id', 'escrow_holdings', 'payout_accounts', ['payout_account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_escrow_holdings_project_id', 'escrow_holdings', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.add_column('omise_recipients', sa.Column('recipient_status', sa.String(length=32), nullable=False, server_default=sa.text("'pending'"), comment='pending | active | disabled | failed'))
    op.add_column('omise_recipients', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('omise_recipients', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    op.add_column('omise_recipients', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    op.add_column('omise_recipients', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('omise_recipients', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb"), comment='Latest Omise recipient payload snapshot'))
    op.add_column('omise_recipients', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.execute("UPDATE omise_recipients SET created_at = COALESCE(created_at, NOW())")
    op.alter_column('omise_recipients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('omise_recipients_omise_recipient_id_key'), 'omise_recipients', type_='unique')
    op.drop_constraint(op.f('omise_recipients_payout_account_id_key'), 'omise_recipients', type_='unique')
    op.alter_column('omise_recipients', 'recipient_status', server_default=None)
    op.alter_column('omise_recipients', 'raw_payload', server_default=None)
    op.alter_column('omise_recipients', 'updated_at', server_default=None)
    op.create_index('ix_omise_recipient_status', 'omise_recipients', ['recipient_status'], unique=False)
    op.create_unique_constraint('uq_omise_recipient_id', 'omise_recipients', ['omise_recipient_id'])
    op.create_unique_constraint('uq_omise_recipient_payout_account', 'omise_recipients', ['payout_account_id'])
    op.drop_constraint(op.f('omise_recipients_payout_account_id_fkey'), 'omise_recipients', type_='foreignkey')
    op.create_foreign_key('fk_omise_recipients_payout_account_id', 'omise_recipients', 'payout_accounts', ['payout_account_id'], ['id'], ondelete='CASCADE')
    op.add_column('payment_transactions', sa.Column('gateway_event_id', sa.String(length=255), nullable=True, comment='Webhook event id from the payment gateway'))
    op.add_column('payment_transactions', sa.Column('idempotency_key', sa.String(length=255), nullable=True, comment='Application-level idempotency key for safe retries'))
    op.add_column('payment_transactions', sa.Column('currency', sa.String(length=3), nullable=False, server_default=sa.text("'THB'"), comment='ISO currency code'))
    op.add_column('payment_transactions', sa.Column('parent_transaction_id', sa.UUID(), nullable=True, comment='Original transaction for refunds or reversals'))
    op.add_column('payment_transactions', sa.Column('processed_at', sa.DateTime(), nullable=True, comment='When our system finished processing this event'))
    op.alter_column('payment_transactions', 'gateway_tx_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Gateway transaction id such as charge / transfer / refund id',
               existing_comment='Transaction ID จาก provider เช่น chrg_xxx (Omise) / pi_xxx (Stripe). NULL = manual',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full webhook or gateway payload for audit and reconciliation',
               existing_comment='Full webhook body จาก gateway — เก็บไว้สำหรับ debug / reconcile',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'fee',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Gateway fee or platform fee charged on this transaction',
               existing_comment='platform fee หรือ gateway fee ที่หักออก',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'net_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Net amount after fees',
               existing_comment='amount - fee = ยอดสุทธิที่ผู้รับได้จริง',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'user_id',
               existing_type=sa.UUID(),
               comment='Primary owner of this transaction record',
               existing_comment='เจ้าของรายการ — client (charge/refund) หรือ freelancer (transfer)',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'reference_type',
               existing_type=sa.VARCHAR(length=30),
               comment='milestone | project | dispute | payout_account',
               existing_comment='milestone | project | dispute',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'gateway_created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When the gateway created the underlying transaction',
               existing_comment='เวลาที่ gateway สร้าง transaction (จาก webhook payload)',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'currency', server_default=None)
    op.create_index('ix_payment_tx_event_id', 'payment_transactions', ['gateway_event_id'], unique=False)
    op.create_index('ix_payment_tx_idempotency', 'payment_transactions', ['idempotency_key'], unique=False)
    op.create_foreign_key('fk_payment_transactions_parent_transaction_id', 'payment_transactions', 'payment_transactions', ['parent_transaction_id'], ['id'], ondelete='SET NULL')
    op.add_column('payout_accounts', sa.Column('currency', sa.String(length=3), nullable=False, server_default=sa.text("'THB'")))
    op.add_column('payout_accounts', sa.Column('country', sa.String(length=2), nullable=False, server_default=sa.text("'TH'")))
    op.add_column('payout_accounts', sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('payout_accounts', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('payout_accounts', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    op.add_column('payout_accounts', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('payout_accounts', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.execute("""
        UPDATE payout_accounts
        SET
            consent_given = COALESCE(consent_given, false),
            status = COALESCE(status, 'pending_verification'),
            created_at = COALESCE(created_at, NOW()),
            updated_at = COALESCE(updated_at, NOW()),
            currency = COALESCE(currency, 'THB'),
            country = COALESCE(country, 'TH'),
            is_default = COALESCE(is_default, false)
    """)
    op.alter_column('payout_accounts', 'bank_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payout_accounts', 'bank_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payout_accounts', 'account_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payout_accounts', 'account_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payout_accounts', 'consent_given',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('payout_accounts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='pending_verification | active | inactive | rejected',
               existing_comment='draft | consented | verified | active | suspended')
    op.alter_column('payout_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('payout_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('payout_accounts', 'currency', server_default=None)
    op.alter_column('payout_accounts', 'country', server_default=None)
    op.alter_column('payout_accounts', 'is_default', server_default=None)
    op.drop_constraint(op.f('payout_accounts_user_id_key'), 'payout_accounts', type_='unique')
    op.create_index('ix_payout_accounts_default', 'payout_accounts', ['user_id', 'is_default'], unique=False)
    op.create_index('ix_payout_accounts_status', 'payout_accounts', ['status'], unique=False)
    op.create_index('ix_payout_accounts_user', 'payout_accounts', ['user_id'], unique=False)
    op.drop_constraint(op.f('payout_accounts_user_id_fkey'), 'payout_accounts', type_='foreignkey')
    op.create_foreign_key('fk_payout_accounts_user_id', 'payout_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_payout_accounts_user_id', 'payout_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('payout_accounts_user_id_fkey'), 'payout_accounts', 'users', ['user_id'], ['id'])
    op.drop_index('ix_payout_accounts_user', table_name='payout_accounts')
    op.drop_index('ix_payout_accounts_status', table_name='payout_accounts')
    op.drop_index('ix_payout_accounts_default', table_name='payout_accounts')
    op.create_unique_constraint(op.f('payout_accounts_user_id_key'), 'payout_accounts', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('payout_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('payout_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('payout_accounts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='draft | consented | verified | active | suspended',
               existing_comment='pending_verification | active | inactive | rejected')
    op.alter_column('payout_accounts', 'consent_given',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('payout_accounts', 'account_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payout_accounts', 'account_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payout_accounts', 'bank_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payout_accounts', 'bank_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('payout_accounts', 'last_used_at')
    op.drop_column('payout_accounts', 'rejection_reason')
    op.drop_column('payout_accounts', 'disabled_at')
    op.drop_column('payout_accounts', 'verified_at')
    op.drop_column('payout_accounts', 'is_default')
    op.drop_column('payout_accounts', 'country')
    op.drop_column('payout_accounts', 'currency')
    op.drop_constraint('fk_payment_transactions_parent_transaction_id', 'payment_transactions', type_='foreignkey')
    op.drop_index('ix_payment_tx_idempotency', table_name='payment_transactions')
    op.drop_index('ix_payment_tx_event_id', table_name='payment_transactions')
    op.alter_column('payment_transactions', 'gateway_created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='เวลาที่ gateway สร้าง transaction (จาก webhook payload)',
               existing_comment='When the gateway created the underlying transaction',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'reference_type',
               existing_type=sa.VARCHAR(length=30),
               comment='milestone | project | dispute',
               existing_comment='milestone | project | dispute | payout_account',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'user_id',
               existing_type=sa.UUID(),
               comment='เจ้าของรายการ — client (charge/refund) หรือ freelancer (transfer)',
               existing_comment='Primary owner of this transaction record',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'net_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='amount - fee = ยอดสุทธิที่ผู้รับได้จริง',
               existing_comment='Net amount after fees',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'fee',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='platform fee หรือ gateway fee ที่หักออก',
               existing_comment='Gateway fee or platform fee charged on this transaction',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full webhook body จาก gateway — เก็บไว้สำหรับ debug / reconcile',
               existing_comment='Full webhook or gateway payload for audit and reconciliation',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'gateway_tx_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Transaction ID จาก provider เช่น chrg_xxx (Omise) / pi_xxx (Stripe). NULL = manual',
               existing_comment='Gateway transaction id such as charge / transfer / refund id',
               existing_nullable=True)
    op.drop_column('payment_transactions', 'processed_at')
    op.drop_column('payment_transactions', 'parent_transaction_id')
    op.drop_column('payment_transactions', 'currency')
    op.drop_column('payment_transactions', 'idempotency_key')
    op.drop_column('payment_transactions', 'gateway_event_id')
    op.drop_constraint('fk_omise_recipients_payout_account_id', 'omise_recipients', type_='foreignkey')
    op.create_foreign_key(op.f('omise_recipients_payout_account_id_fkey'), 'omise_recipients', 'payout_accounts', ['payout_account_id'], ['id'])
    op.drop_constraint('uq_omise_recipient_payout_account', 'omise_recipients', type_='unique')
    op.drop_constraint('uq_omise_recipient_id', 'omise_recipients', type_='unique')
    op.drop_index('ix_omise_recipient_status', table_name='omise_recipients')
    op.create_unique_constraint(op.f('omise_recipients_payout_account_id_key'), 'omise_recipients', ['payout_account_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('omise_recipients_omise_recipient_id_key'), 'omise_recipients', ['omise_recipient_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('omise_recipients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('omise_recipients', 'updated_at')
    op.drop_column('omise_recipients', 'raw_payload')
    op.drop_column('omise_recipients', 'failure_reason')
    op.drop_column('omise_recipients', 'last_synced_at')
    op.drop_column('omise_recipients', 'disabled_at')
    op.drop_column('omise_recipients', 'verified_at')
    op.drop_column('omise_recipients', 'recipient_status')
    op.drop_constraint('fk_escrow_holdings_project_id', 'escrow_holdings', type_='foreignkey')
    op.drop_constraint('fk_escrow_holdings_payout_account_id', 'escrow_holdings', type_='foreignkey')
    op.drop_constraint('fk_escrow_holdings_omise_recipient_ref_id', 'escrow_holdings', type_='foreignkey')
    op.drop_index('ix_escrow_project', table_name='escrow_holdings')
    op.alter_column('escrow_holdings', 'released_by',
               existing_type=sa.UUID(),
               comment='admin UUID ถ้า manual action, NULL ถ้า auto-release',
               existing_comment='Admin user id for manual release or refund',
               existing_nullable=True)
    op.alter_column('escrow_holdings', 'release_tx_id',
               existing_type=sa.UUID(),
               comment='transaction ที่ settle (transfer หรือ refund) — NULL ถ้ายัง HELD',
               existing_comment='Settlement transaction for transfer or refund',
               existing_nullable=True)
    op.alter_column('escrow_holdings', 'charge_tx_id',
               existing_type=sa.UUID(),
               comment='transaction ที่ client ชำระ (charge succeeded)',
               existing_comment='Funding transaction from the client',
               existing_nullable=False)
    op.alter_column('escrow_holdings', 'freelancer_id',
               existing_type=sa.UUID(),
               comment='ฝั่งรับงาน — คนที่จะได้รับเงิน',
               existing_comment='Freelancer receiving the payout after release',
               existing_nullable=False)
    op.alter_column('escrow_holdings', 'client_id',
               existing_type=sa.UUID(),
               comment='ฝั่งจ้าง — คนที่ชำระเงิน',
               existing_comment='Client funding the milestone',
               existing_nullable=False)
    op.drop_column('escrow_holdings', 'last_status_changed_at')
    op.drop_column('escrow_holdings', 'auto_release_at')
    op.drop_column('escrow_holdings', 'currency')
    op.drop_column('escrow_holdings', 'net_payout_amount')
    op.drop_column('escrow_holdings', 'platform_fee_amount')
    op.drop_column('escrow_holdings', 'omise_recipient_ref_id')
    op.drop_column('escrow_holdings', 'payout_account_id')
    op.drop_column('escrow_holdings', 'project_id')
    # ### end Alembic commands ###
