"""

Revision ID: d37127c04040
Revises: a1b2c3d4e5f6
Create Date: 2026-04-03 10:00:00.236851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd37127c04040'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_read_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_read_receipt')
    )
    op.create_index('ix_read_receipts_user_message', 'message_read_receipts', ['user_id', 'message_id'], unique=False)
    op.add_column('chat_messages', sa.Column('reply_to_message_id', sa.UUID(), nullable=True))
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='text | file | system')
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='เนื้อหาข้อความ — ถ้าเป็น file จะเป็น URL หรือ JSON metadata')
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('chat_messages', 'edited_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='เวลาที่แก้ไขข้อความ — set manual ที่ service layer',
               existing_nullable=True)
    op.alter_column('chat_messages', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment="soft delete — แสดงเป็น 'deleted message' แทนลบจริง",
               existing_nullable=True)
    op.create_index('ix_chat_messages_room_created', 'chat_messages', ['chat_room_id', 'created_at'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'chat_messages', ['reply_to_message_id'], ['id'])
    op.drop_column('chat_messages', 'read_at')
    op.add_column('chat_participants', sa.Column('left_at', sa.DateTime(), nullable=True, comment='เวลาออกจากห้อง — NULL = ยังอยู่ในห้อง'))
    op.alter_column('chat_participants', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('chat_participants', 'last_read_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='อ่านข้อความล่าสุดถึงเวลานี้ — ใช้คำนวณจำนวนข้อความที่ยังไม่อ่าน',
               existing_nullable=True)
    op.create_unique_constraint('uq_chat_participant', 'chat_participants', ['chat_room_id', 'user_id'])
    op.alter_column('chat_rooms', 'peer_user_id',
               existing_type=sa.UUID(),
               comment='สำหรับห้อง DM, peer_user_id จะเก็บ ID ของผู้ใช้คนอื่นที่เป็นคู่สนทนา (ไม่ใช่เจ้าของห้อง) เพื่อให้ง่ายต่อการค้นหาและจัดการห้อง DM โดยไม่ต้องเชื่อมโยงกับตารางผู้ใช้หลายครั้ง',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'name',
               existing_type=sa.VARCHAR(),
               comment='ชื่อห้องสำหรับแชทกลุ่ม หรือชื่อเล่นสำหรับ DM (ถ้าไม่ระบุจะใช้ชื่อของ peer_user_id สำหรับ DM)',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('freelancer_portfolios', sa.Column('cover_image_url', sa.String(), nullable=True))
    op.add_column('freelancer_portfolios', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('freelancer_portfolios', sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_index(op.f('ix_freelancer_portfolios_user_id'), table_name='freelancer_portfolios')
    op.create_index(op.f('ix_freelancer_portfolios_user_id'), 'freelancer_portfolios', ['user_id'], unique=False)
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(), nullable=True, comment='เวลาที่อ่าน — set พร้อมกับ is_read=True ที่ service layer'))
    op.add_column('notifications', sa.Column('expires_at', sa.DateTime(), nullable=True, comment='วันหมดอายุของ notification — cleanup job ใช้ลบ record นี้อัตโนมัติ'))
    op.alter_column('notifications', 'reference_type',
               existing_type=sa.VARCHAR(),
               comment='ประเภทของ entity ที่เกี่ยวข้อง เช่น project | offer | milestone | message',
               existing_nullable=True)
    op.alter_column('notifications', 'reference_id',
               existing_type=sa.VARCHAR(),
               comment='UUID stored as string สำหรับอ้างอิงไปยัง entity ที่เกี่ยวข้อง',
               existing_nullable=True)
    op.drop_index(op.f('ix_notifications_actor_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.add_column('portfolio_files', sa.Column('title', sa.String(), nullable=True))
    op.add_column('portfolio_files', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('portfolio_files', sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.alter_column('portfolio_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_freelance_skills', 'tagline',
               existing_type=sa.VARCHAR(),
               comment='tagline สั้นๆ ไม่เกิน 160 ตัวอักษร',
               existing_comment='tagline สั้นๆ แสดงความเชี่ยวชาญหรือจุดเด่นของ',
               existing_nullable=True)
    op.alter_column('user_freelance_skills', 'skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               comment="รายการทักษะ เช่น ['Python', 'React']",
               existing_comment="รายการทักษะของผู้ใช้ เช่น ['Python', 'React', ...]")
    op.alter_column('user_freelance_skills', 'hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='อัตราค่าบริการต่อชั่วโมง (หน่วย: บาท)',
               existing_comment='อัตราค่าบริการต่อชั่วโมงของผู้ใช้',
               existing_nullable=True)
    op.alter_column('user_freelance_skills', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='true = แสดงบน /explore/freelancers',
               existing_comment='freelancer opt-in to appear in public listings')
    op.alter_column('user_freelance_skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_freelance_skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_user_freelance_skills_user_id'), table_name='user_freelance_skills')
    op.create_index('ix_freelance_hourly_rate', 'user_freelance_skills', ['hourly_rate'], unique=False)
    op.create_index('ix_freelance_public', 'user_freelance_skills', ['is_public'], unique=False)
    op.create_unique_constraint('uq_user_freelance_skill', 'user_freelance_skills', ['user_id'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               comment='ชื่อผู้ใช้ที่ไม่ซ้ำกัน (@handle)',
               existing_nullable=True)
    # Backfill NULL emails before setting NOT NULL
    op.execute("UPDATE users SET email = keycloak_user_id || '@placeholder.local' WHERE email IS NULL")
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default=None,
               comment='อีเมลของผู้ใช้',
               existing_comment='อีเมลของผู้ใช้ และติดต่อ',
               existing_server_default=sa.text("'test@example.com'::character varying"))
    # Backfill NULL firstnames before setting NOT NULL
    op.execute("UPDATE users SET firstname = 'Unknown' WHERE firstname IS NULL")
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='ชื่อจริง',
               existing_comment='ชื่อจริงของผู้ใช้')
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               comment='นามสกุล',
               existing_comment='นามสกุลของผู้ใช้',
               existing_nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               comment='ชื่อที่แสดงบนแพลตฟอร์ม — auto-fill จาก firstname+lastname ถ้าไม่ระบุ',
               existing_comment='ชื่อที่แสดงบนแพลตฟอร์ม (ถ้าไม่ระบุจะใช้ชื่อจริง)',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               comment='URL รูปโปรไฟล์',
               existing_comment='URL ของรูปโปรไฟล์ผู้ใช้',
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               comment='Bio / แนะนำตัวเอง',
               existing_comment='ข้อมูลอธิบายตัวตน',
               existing_nullable=True)
    # Backfill status, created_at, updated_at before setting NOT NULL
    op.execute("UPDATE users SET status = 'active' WHERE status IS NULL")
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE users SET updated_at = NOW() WHERE updated_at IS NULL")
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='active | inactive | banned')
    # Backfill boolean/status columns before setting NOT NULL
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")
    op.execute("UPDATE users SET phone_verified = false WHERE phone_verified IS NULL")
    op.execute("UPDATE users SET kyc_status = 'pending' WHERE kyc_status IS NULL")
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'phone_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'kyc_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='unverified | pending | verified | rejected')
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='soft delete timestamp — NULL = ยังใช้งานอยู่',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_deleted_at', table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='soft delete timestamp — NULL = ยังใช้งานอยู่',
               existing_nullable=True)
    op.alter_column('users', 'kyc_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='unverified | pending | verified | rejected')
    op.alter_column('users', 'phone_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='active | inactive | banned')
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               comment='ข้อมูลอธิบายตัวตน',
               existing_comment='Bio / แนะนำตัวเอง',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               comment='URL ของรูปโปรไฟล์ผู้ใช้',
               existing_comment='URL รูปโปรไฟล์',
               existing_nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               comment='ชื่อที่แสดงบนแพลตฟอร์ม (ถ้าไม่ระบุจะใช้ชื่อจริง)',
               existing_comment='ชื่อที่แสดงบนแพลตฟอร์ม — auto-fill จาก firstname+lastname ถ้าไม่ระบุ',
               existing_nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               comment='นามสกุลของผู้ใช้',
               existing_comment='นามสกุล',
               existing_nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='ชื่อจริงของผู้ใช้',
               existing_comment='ชื่อจริง')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='อีเมลของผู้ใช้ และติดต่อ',
               existing_comment='อีเมลของผู้ใช้',
               existing_server_default=sa.text("'test@example.com'::character varying"))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ชื่อผู้ใช้ที่ไม่ซ้ำกัน (@handle)',
               existing_nullable=True)
    op.drop_constraint('uq_user_freelance_skill', 'user_freelance_skills', type_='unique')
    op.drop_index('ix_freelance_public', table_name='user_freelance_skills')
    op.drop_index('ix_freelance_hourly_rate', table_name='user_freelance_skills')
    op.create_index(op.f('ix_user_freelance_skills_user_id'), 'user_freelance_skills', ['user_id'], unique=False)
    op.alter_column('user_freelance_skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_freelance_skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_freelance_skills', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='freelancer opt-in to appear in public listings',
               existing_comment='true = แสดงบน /explore/freelancers')
    op.alter_column('user_freelance_skills', 'hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='อัตราค่าบริการต่อชั่วโมงของผู้ใช้',
               existing_comment='อัตราค่าบริการต่อชั่วโมง (หน่วย: บาท)',
               existing_nullable=True)
    op.alter_column('user_freelance_skills', 'skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment="รายการทักษะของผู้ใช้ เช่น ['Python', 'React', ...]",
               existing_comment="รายการทักษะ เช่น ['Python', 'React']")
    op.alter_column('user_freelance_skills', 'tagline',
               existing_type=sa.VARCHAR(),
               comment='tagline สั้นๆ แสดงความเชี่ยวชาญหรือจุดเด่นของ',
               existing_comment='tagline สั้นๆ ไม่เกิน 160 ตัวอักษร',
               existing_nullable=True)
    op.alter_column('portfolio_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('portfolio_files', 'sort_order')
    op.drop_column('portfolio_files', 'description')
    op.drop_column('portfolio_files', 'title')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_actor_id'), 'notifications', ['actor_id'], unique=False)
    op.alter_column('notifications', 'reference_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='UUID stored as string สำหรับอ้างอิงไปยัง entity ที่เกี่ยวข้อง',
               existing_nullable=True)
    op.alter_column('notifications', 'reference_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ประเภทของ entity ที่เกี่ยวข้อง เช่น project | offer | milestone | message',
               existing_nullable=True)
    op.drop_column('notifications', 'expires_at')
    op.drop_column('notifications', 'read_at')
    op.drop_index(op.f('ix_freelancer_portfolios_user_id'), table_name='freelancer_portfolios')
    op.create_index(op.f('ix_freelancer_portfolios_user_id'), 'freelancer_portfolios', ['user_id'], unique=True)
    op.drop_column('freelancer_portfolios', 'sort_order')
    op.drop_column('freelancer_portfolios', 'is_public')
    op.drop_column('freelancer_portfolios', 'cover_image_url')
    op.alter_column('chat_rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('chat_rooms', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ชื่อห้องสำหรับแชทกลุ่ม หรือชื่อเล่นสำหรับ DM (ถ้าไม่ระบุจะใช้ชื่อของ peer_user_id สำหรับ DM)',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'peer_user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='สำหรับห้อง DM, peer_user_id จะเก็บ ID ของผู้ใช้คนอื่นที่เป็นคู่สนทนา (ไม่ใช่เจ้าของห้อง) เพื่อให้ง่ายต่อการค้นหาและจัดการห้อง DM โดยไม่ต้องเชื่อมโยงกับตารางผู้ใช้หลายครั้ง',
               existing_nullable=True)
    op.drop_constraint('uq_chat_participant', 'chat_participants', type_='unique')
    op.alter_column('chat_participants', 'last_read_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='อ่านข้อความล่าสุดถึงเวลานี้ — ใช้คำนวณจำนวนข้อความที่ยังไม่อ่าน',
               existing_nullable=True)
    op.alter_column('chat_participants', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('chat_participants', 'left_at')
    op.add_column('chat_messages', sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index('ix_chat_messages_room_created', table_name='chat_messages')
    op.alter_column('chat_messages', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment="soft delete — แสดงเป็น 'deleted message' แทนลบจริง",
               existing_nullable=True)
    op.alter_column('chat_messages', 'edited_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='เวลาที่แก้ไขข้อความ — set manual ที่ service layer',
               existing_nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True,
               comment=None,
               existing_comment='เนื้อหาข้อความ — ถ้าเป็น file จะเป็น URL หรือ JSON metadata')
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='text | file | system')
    op.drop_column('chat_messages', 'reply_to_message_id')
    op.drop_index('ix_read_receipts_user_message', table_name='message_read_receipts')
    op.drop_table('message_read_receipts')
    # ### end Alembic commands ###
