"""align_comments_and_column_types_with_models

Revision ID: de046cb5ea06
Revises: 2d4e6f7a8b90
Create Date: 2026-04-05 11:42:39.197564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de046cb5ea06'
down_revision: Union[str, Sequence[str], None] = '2d4e6f7a8b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               comment='เนื้อหาข้อความ — ถ้าเป็น file จะเป็น URL หรือ JSON metadata',
               existing_nullable=False)
    op.alter_column('chat_messages', 'edited_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='เวลาที่แก้ไขข้อความ — set manual ที่ service layer',
               existing_nullable=True)
    op.alter_column('chat_messages', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment="soft delete — แสดงเป็น 'deleted message' แทนลบจริง",
               existing_nullable=True)
    op.alter_column('chat_participants', 'left_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='เวลาออกจากห้อง — NULL = ยังอยู่ในห้อง',
               existing_nullable=True)
    op.alter_column('chat_participants', 'last_read_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='อ่านข้อความล่าสุดถึงเวลานี้ — ใช้คำนวณจำนวนข้อความที่ยังไม่อ่าน',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'room_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='dm | project | main',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'peer_user_id',
               existing_type=sa.UUID(),
               comment='สำหรับห้อง DM, peer_user_id จะเก็บ ID ของผู้ใช้คนอื่นที่เป็นคู่สนทนา (ไม่ใช่เจ้าของห้อง) เพื่อให้ง่ายต่อการค้นหาและจัดการห้อง DM โดยไม่ต้องเชื่อมโยงกับตารางผู้ใช้หลายครั้ง',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'name',
               existing_type=sa.VARCHAR(),
               comment='ชื่อห้องสำหรับแชทกลุ่ม หรือชื่อเล่นสำหรับ DM (ถ้าไม่ระบุจะใช้ชื่อของ peer_user_id สำหรับ DM)',
               existing_nullable=True)
    op.alter_column('community_post_attachments', 'file_url',
               existing_type=sa.VARCHAR(),
               comment='URL ของไฟล์ (เก็บใน MinIO / S3)',
               existing_nullable=False)
    op.alter_column('community_post_attachments', 'file_type',
               existing_type=sa.VARCHAR(),
               comment='ประเภทไฟล์ เช่น image | video | document',
               existing_nullable=False,
               existing_server_default=sa.text("'image'::character varying"))
    op.alter_column('community_post_attachments', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='ลำดับการแสดงผล — น้อยก่อน',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('community_post_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='วันที่สร้างไฟล์แนบ',
               existing_nullable=False)
    op.alter_column('community_post_comments', 'parent_comment_id',
               existing_type=sa.UUID(),
               comment='สำหรับคอมเมนต์ที่เป็นการตอบกลับ (reply) จะเก็บ ID ของคอมเมนต์ต้นทางที่ถูกตอบกลับ',
               existing_nullable=True)
    op.alter_column('community_post_comments', 'content',
               existing_type=sa.TEXT(),
               comment='เนื้อหาคอมเมนต์',
               existing_nullable=False)
    op.alter_column('community_post_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='วันที่สร้างคอมเมนต์',
               existing_nullable=False)
    op.alter_column('community_post_comments', 'edited_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='วันที่แก้ไข content จริงๆ — set manual ที่ service layer',
               existing_nullable=True)
    op.alter_column('community_post_comments', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='soft delete — ถ้ามีค่าหมายถึงถูกลบแล้ว แต่ replies ยังแสดงอยู่ได้',
               existing_nullable=True)
    op.alter_column('community_post_reactions', 'comment_id',
               existing_type=sa.UUID(),
               comment='ถ้า react ที่ comment จะมีค่า, ถ้า react ที่ post จะเป็น null',
               existing_nullable=True)
    op.alter_column('community_post_reactions', 'reaction_type',
               existing_type=postgresql.ENUM('LIKE', 'DISLIKE', name='communityreactiontype'),
               comment='ประเภทของปฏิกิริยา เช่น like | dislike',
               existing_nullable=False)
    op.alter_column('community_post_reactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='วันที่สร้างปฏิกิริยา',
               existing_nullable=False)
    op.alter_column('community_post_views', 'viewed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='วันที่ดูโพสต์ล่าสุด — อัปเดตทุกครั้งที่ดู (ใช้กับ logic 30 นาที ที่ service layer)',
               existing_nullable=False)
    op.alter_column('community_posts', 'author_id',
               existing_type=sa.UUID(),
               comment='ผู้เขียนโพสต์',
               existing_nullable=False)
    op.alter_column('community_posts', 'category',
               existing_type=sa.VARCHAR(),
               comment='ประเภทโพสต์ เช่น general | artwork | coding | design | writing',
               existing_nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('community_posts', 'content',
               existing_type=sa.TEXT(),
               comment='เนื้อหาโพสต์ (text)',
               existing_nullable=True)
    op.alter_column('community_posts', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment='true = แสดงสาธารณะ, false = เฉพาะตัวเอง',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('community_posts', 'view_count',
               existing_type=sa.INTEGER(),
               comment='จำนวน view แบบ denormalized — increment ที่ service layer ด้วย UPDATE ... SET view_count = view_count + 1',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('community_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='วันที่สร้างโพสต์',
               existing_nullable=False)
    op.alter_column('community_posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='วันที่ DB row ถูก touch ล่าสุด (รวมถึงการ increment view_count)',
               existing_nullable=True)
    op.alter_column('community_posts', 'edited_at',
               existing_type=postgresql.TIMESTAMP(),
               comment="วันที่ user แก้ไข content จริงๆ — set manual ที่ service layer เท่านั้น แสดงบน UI ว่า 'แก้ไขแล้ว'",
               existing_nullable=True)
    op.alter_column('community_posts', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='soft delete — ถ้ามีค่าหมายถึงถูกลบแล้ว',
               existing_nullable=True)
    op.alter_column('escrow_holdings', 'client_id',
               existing_type=sa.UUID(),
               comment='ฝั่งจ้าง — คนที่ชำระเงิน',
               existing_nullable=False)
    op.alter_column('escrow_holdings', 'freelancer_id',
               existing_type=sa.UUID(),
               comment='ฝั่งรับงาน — คนที่จะได้รับเงิน',
               existing_nullable=False)
    op.alter_column('escrow_holdings', 'charge_tx_id',
               existing_type=sa.UUID(),
               comment='transaction ที่ client ชำระ (charge succeeded)',
               existing_nullable=False)
    op.alter_column('escrow_holdings', 'release_tx_id',
               existing_type=sa.UUID(),
               comment='transaction ที่ settle (transfer หรือ refund) — NULL ถ้ายัง HELD',
               existing_nullable=True)
    op.alter_column('escrow_holdings', 'released_by',
               existing_type=sa.UUID(),
               comment='admin UUID ถ้า manual action, NULL ถ้า auto-release',
               existing_nullable=True)
    op.alter_column('job_assignments', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='accepted | in_progress | completed | cancelled',
               existing_nullable=True)
    op.alter_column('job_milestones', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='pending | submitted | approved | rejected',
               existing_nullable=True)
    op.alter_column('job_offers', 'offer_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='proposal | direct_invite',
               existing_nullable=True)
    op.alter_column('job_offers', 'scope',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('job_offers', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('job_offers', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='pending | accepted | rejected | cancelled',
               existing_nullable=True)
    op.alter_column('job_offers', 'rejection_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('jobs', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='draft | open | closed | cancelled',
               existing_nullable=True)
    op.alter_column('jobs', 'deadline_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Optional deadline date specified by client',
               existing_nullable=True)
    op.alter_column('milestone_submissions', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='submitted | approved | rejected',
               existing_nullable=True)
    op.alter_column('notifications', 'reference_type',
               existing_type=sa.VARCHAR(),
               comment='ประเภทของ entity ที่เกี่ยวข้อง เช่น project | offer | milestone | message',
               existing_nullable=True)
    op.alter_column('notifications', 'reference_id',
               existing_type=sa.VARCHAR(),
               comment='UUID stored as string สำหรับอ้างอิงไปยัง entity ที่เกี่ยวข้อง',
               existing_nullable=True)
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='เวลาที่อ่าน — set พร้อมกับ is_read=True ที่ service layer',
               existing_nullable=True)
    op.alter_column('notifications', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='วันหมดอายุของ notification — cleanup job ใช้ลบ record นี้อัตโนมัติ',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'gateway_provider',
               existing_type=sa.VARCHAR(length=20),
               comment='omise | stripe | promptpay | manual',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'gateway_tx_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Transaction ID จาก provider เช่น chrg_xxx (Omise) / pi_xxx (Stripe). NULL = manual',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full webhook body จาก gateway — เก็บไว้สำหรับ debug / reconcile',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='charge | transfer | refund | reversal',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'fee',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='platform fee หรือ gateway fee ที่หักออก',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'net_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='amount - fee = ยอดสุทธิที่ผู้รับได้จริง',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'user_id',
               existing_type=sa.UUID(),
               comment='เจ้าของรายการ — client (charge/refund) หรือ freelancer (transfer)',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'reference_type',
               existing_type=sa.VARCHAR(length=30),
               comment='milestone | project | dispute',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'gateway_created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='เวลาที่ gateway สร้าง transaction (จาก webhook payload)',
               existing_nullable=True)
    op.alter_column('transactions', 'direction',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='debit | credit',
               existing_nullable=True)
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='hold | release | refund | payout',
               existing_nullable=True)
    op.alter_column('user_freelance_skills', 'tagline',
               existing_type=sa.VARCHAR(length=160),
               comment='tagline สั้นๆ ไม่เกิน 160 ตัวอักษร',
               existing_nullable=True)
    op.alter_column('user_freelance_skills', 'skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="รายการทักษะ เช่น ['Python', 'React']",
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('user_freelance_skills', 'hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='อัตราค่าบริการต่อชั่วโมง (หน่วย: บาท)',
               existing_nullable=True)
    op.alter_column('user_freelance_skills', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment='true = แสดงบน /explore/freelancers',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'keycloak_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               comment='ชื่อผู้ใช้ที่ไม่ซ้ำกัน (@handle)',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='อีเมลของผู้ใช้',
               existing_nullable=False)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               comment='ชื่อจริง',
               existing_nullable=False)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               comment='นามสกุล',
               existing_nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               comment='ชื่อที่แสดงบนแพลตฟอร์ม — auto-fill จาก firstname+lastname ถ้าไม่ระบุ',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               comment='URL รูปโปรไฟล์',
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               comment='Bio / แนะนำตัวเอง',
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               comment='active | inactive | banned',
               existing_comment='active | suspended | deleted',
               existing_nullable=False)
    op.alter_column('users', 'kyc_status',
               existing_type=sa.VARCHAR(),
               comment='unverified | pending | verified | rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'unverified'::character varying"))
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='soft delete timestamp — NULL = ยังใช้งานอยู่',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='soft delete timestamp — NULL = ยังใช้งานอยู่',
               existing_nullable=True)
    op.alter_column('users', 'kyc_status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='unverified | pending | verified | rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'unverified'::character varying"))
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               comment='active | suspended | deleted',
               existing_comment='active | inactive | banned',
               existing_nullable=False)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Bio / แนะนำตัวเอง',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='URL รูปโปรไฟล์',
               existing_nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ชื่อที่แสดงบนแพลตฟอร์ม — auto-fill จาก firstname+lastname ถ้าไม่ระบุ',
               existing_nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='นามสกุล',
               existing_nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ชื่อจริง',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='อีเมลของผู้ใช้',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ชื่อผู้ใช้ที่ไม่ซ้ำกัน (@handle)',
               existing_nullable=True)
    op.alter_column('users', 'keycloak_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_freelance_skills', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='true = แสดงบน /explore/freelancers',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_freelance_skills', 'hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='อัตราค่าบริการต่อชั่วโมง (หน่วย: บาท)',
               existing_nullable=True)
    op.alter_column('user_freelance_skills', 'skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="รายการทักษะ เช่น ['Python', 'React']",
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('user_freelance_skills', 'tagline',
               existing_type=sa.VARCHAR(length=160),
               comment=None,
               existing_comment='tagline สั้นๆ ไม่เกิน 160 ตัวอักษร',
               existing_nullable=True)
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(),
               comment='hold | release | refund | payout',
               existing_nullable=True)
    op.alter_column('transactions', 'direction',
               existing_type=sa.VARCHAR(),
               comment='debit | credit',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'gateway_created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='เวลาที่ gateway สร้าง transaction (จาก webhook payload)',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'reference_type',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='milestone | project | dispute',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='เจ้าของรายการ — client (charge/refund) หรือ freelancer (transfer)',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'net_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='amount - fee = ยอดสุทธิที่ผู้รับได้จริง',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'fee',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='platform fee หรือ gateway fee ที่หักออก',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='charge | transfer | refund | reversal',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Full webhook body จาก gateway — เก็บไว้สำหรับ debug / reconcile',
               existing_nullable=False)
    op.alter_column('payment_transactions', 'gateway_tx_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Transaction ID จาก provider เช่น chrg_xxx (Omise) / pi_xxx (Stripe). NULL = manual',
               existing_nullable=True)
    op.alter_column('payment_transactions', 'gateway_provider',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='omise | stripe | promptpay | manual',
               existing_nullable=False)
    op.alter_column('notifications', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='วันหมดอายุของ notification — cleanup job ใช้ลบ record นี้อัตโนมัติ',
               existing_nullable=True)
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='เวลาที่อ่าน — set พร้อมกับ is_read=True ที่ service layer',
               existing_nullable=True)
    op.alter_column('notifications', 'reference_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='UUID stored as string สำหรับอ้างอิงไปยัง entity ที่เกี่ยวข้อง',
               existing_nullable=True)
    op.alter_column('notifications', 'reference_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ประเภทของ entity ที่เกี่ยวข้อง เช่น project | offer | milestone | message',
               existing_nullable=True)
    op.alter_column('milestone_submissions', 'status',
               existing_type=sa.VARCHAR(),
               comment='submitted | approved | rejected',
               existing_nullable=True)
    op.alter_column('jobs', 'deadline_date',
               existing_type=sa.DATE(),
               comment='Optional deadline date specified by client',
               existing_nullable=True)
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(),
               comment='draft | open | closed | cancelled',
               existing_nullable=True)
    op.alter_column('jobs', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('job_offers', 'rejection_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('job_offers', 'status',
               existing_type=sa.VARCHAR(),
               comment='pending | accepted | rejected | cancelled',
               existing_nullable=True)
    op.alter_column('job_offers', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('job_offers', 'scope',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('job_offers', 'offer_type',
               existing_type=sa.VARCHAR(),
               comment='proposal | direct_invite',
               existing_nullable=True)
    op.alter_column('job_milestones', 'status',
               existing_type=sa.VARCHAR(),
               comment='pending | submitted | approved | rejected',
               existing_nullable=True)
    op.alter_column('job_assignments', 'status',
               existing_type=sa.VARCHAR(),
               comment='accepted | in_progress | completed | cancelled',
               existing_nullable=True)
    op.alter_column('escrow_holdings', 'released_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='admin UUID ถ้า manual action, NULL ถ้า auto-release',
               existing_nullable=True)
    op.alter_column('escrow_holdings', 'release_tx_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='transaction ที่ settle (transfer หรือ refund) — NULL ถ้ายัง HELD',
               existing_nullable=True)
    op.alter_column('escrow_holdings', 'charge_tx_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='transaction ที่ client ชำระ (charge succeeded)',
               existing_nullable=False)
    op.alter_column('escrow_holdings', 'freelancer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ฝั่งรับงาน — คนที่จะได้รับเงิน',
               existing_nullable=False)
    op.alter_column('escrow_holdings', 'client_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ฝั่งจ้าง — คนที่ชำระเงิน',
               existing_nullable=False)
    op.alter_column('community_posts', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='soft delete — ถ้ามีค่าหมายถึงถูกลบแล้ว',
               existing_nullable=True)
    op.alter_column('community_posts', 'edited_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment="วันที่ user แก้ไข content จริงๆ — set manual ที่ service layer เท่านั้น แสดงบน UI ว่า 'แก้ไขแล้ว'",
               existing_nullable=True)
    op.alter_column('community_posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='วันที่ DB row ถูก touch ล่าสุด (รวมถึงการ increment view_count)',
               existing_nullable=True)
    op.alter_column('community_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='วันที่สร้างโพสต์',
               existing_nullable=False)
    op.alter_column('community_posts', 'view_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='จำนวน view แบบ denormalized — increment ที่ service layer ด้วย UPDATE ... SET view_count = view_count + 1',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('community_posts', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='true = แสดงสาธารณะ, false = เฉพาะตัวเอง',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('community_posts', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='เนื้อหาโพสต์ (text)',
               existing_nullable=True)
    op.alter_column('community_posts', 'category',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ประเภทโพสต์ เช่น general | artwork | coding | design | writing',
               existing_nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('community_posts', 'author_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ผู้เขียนโพสต์',
               existing_nullable=False)
    op.alter_column('community_post_views', 'viewed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='วันที่ดูโพสต์ล่าสุด — อัปเดตทุกครั้งที่ดู (ใช้กับ logic 30 นาที ที่ service layer)',
               existing_nullable=False)
    op.alter_column('community_post_reactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='วันที่สร้างปฏิกิริยา',
               existing_nullable=False)
    op.alter_column('community_post_reactions', 'reaction_type',
               existing_type=postgresql.ENUM('LIKE', 'DISLIKE', name='communityreactiontype'),
               comment=None,
               existing_comment='ประเภทของปฏิกิริยา เช่น like | dislike',
               existing_nullable=False)
    op.alter_column('community_post_reactions', 'comment_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ถ้า react ที่ comment จะมีค่า, ถ้า react ที่ post จะเป็น null',
               existing_nullable=True)
    op.alter_column('community_post_comments', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='soft delete — ถ้ามีค่าหมายถึงถูกลบแล้ว แต่ replies ยังแสดงอยู่ได้',
               existing_nullable=True)
    op.alter_column('community_post_comments', 'edited_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='วันที่แก้ไข content จริงๆ — set manual ที่ service layer',
               existing_nullable=True)
    op.alter_column('community_post_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='วันที่สร้างคอมเมนต์',
               existing_nullable=False)
    op.alter_column('community_post_comments', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='เนื้อหาคอมเมนต์',
               existing_nullable=False)
    op.alter_column('community_post_comments', 'parent_comment_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='สำหรับคอมเมนต์ที่เป็นการตอบกลับ (reply) จะเก็บ ID ของคอมเมนต์ต้นทางที่ถูกตอบกลับ',
               existing_nullable=True)
    op.alter_column('community_post_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='วันที่สร้างไฟล์แนบ',
               existing_nullable=False)
    op.alter_column('community_post_attachments', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ลำดับการแสดงผล — น้อยก่อน',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('community_post_attachments', 'file_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ประเภทไฟล์ เช่น image | video | document',
               existing_nullable=False,
               existing_server_default=sa.text("'image'::character varying"))
    op.alter_column('community_post_attachments', 'file_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='URL ของไฟล์ (เก็บใน MinIO / S3)',
               existing_nullable=False)
    op.alter_column('chat_rooms', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ชื่อห้องสำหรับแชทกลุ่ม หรือชื่อเล่นสำหรับ DM (ถ้าไม่ระบุจะใช้ชื่อของ peer_user_id สำหรับ DM)',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'peer_user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='สำหรับห้อง DM, peer_user_id จะเก็บ ID ของผู้ใช้คนอื่นที่เป็นคู่สนทนา (ไม่ใช่เจ้าของห้อง) เพื่อให้ง่ายต่อการค้นหาและจัดการห้อง DM โดยไม่ต้องเชื่อมโยงกับตารางผู้ใช้หลายครั้ง',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'room_type',
               existing_type=sa.VARCHAR(),
               comment='dm | project | main',
               existing_nullable=True)
    op.alter_column('chat_participants', 'last_read_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='อ่านข้อความล่าสุดถึงเวลานี้ — ใช้คำนวณจำนวนข้อความที่ยังไม่อ่าน',
               existing_nullable=True)
    op.alter_column('chat_participants', 'left_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='เวลาออกจากห้อง — NULL = ยังอยู่ในห้อง',
               existing_nullable=True)
    op.alter_column('chat_messages', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment="soft delete — แสดงเป็น 'deleted message' แทนลบจริง",
               existing_nullable=True)
    op.alter_column('chat_messages', 'edited_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='เวลาที่แก้ไขข้อความ — set manual ที่ service layer',
               existing_nullable=True)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='เนื้อหาข้อความ — ถ้าเป็น file จะเป็น URL หรือ JSON metadata',
               existing_nullable=False)
    # ### end Alembic commands ###
